name: DRdung
version: 1.1
main: com.dreel.DRdung.DRdung
api-version: 1.16
depend: [WorldEdit, WorldGuard]
commands:
  drdung:
    description: Главная команда плагина
    permission: drdang.admin